---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: keycloak-app-env
  name: keycloak-app-env
  namespace: infrastructure
data:

  KEYCLOAK_ADMIN: "<keycloak-user>"
  KEYCLOAK_ADMIN_PASSWORD: "<keycloak-password>"
  KC_HOSTNAME: "<Your-Host-Name Or Your-Domain-Name>"
  KC_PROXY: "edge"
  KC_DB: "mariadb"
  KC_DB_URL_DATABASE: "<keycloak-db-name>"
  KC_DB_URL_HOST: "mariadb-service"
  KC_DB_URL_PORT: "3306"
  KC_DB_USERNAME: "root"
  KC_DB_PASSWORD: "<keycloak-root-password>"
  KC_CACHE: "local"
  KC_CACHE_STACK: "kubernetes"
  KC_FEATURES: "authorization,token-exchange,docker,impersonation,declarative-user-profile,web-authn,client-policies,admin-api,js-adapter,update-email,ciba"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
  namespace: infrastructure
data:

  primary.cnf: |
    [mariadb]
    log-bin                         # enable binary logging
    log-basename=my-mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)

  replica.cnf: |
    [mariadb]
    log-basename=my-mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)

  primary.sql: |
    CREATE USER 'repluser'@'%' IDENTIFIED BY 'replsecret';
    GRANT REPLICATION REPLICA ON *.* TO 'repluser'@'%';
    CREATE DATABASE primary_db;

  secondary.sql: |
    # We have to know name of sts (`mariadb-sts`) and 
    # service `mariadb-service` in advance as an FQDN.
    # No need to use master_port
    CHANGE MASTER TO 
    MASTER_HOST='mariadb-sts-0.mariadb-service.infrastructure.svc.cluster.local',
    MASTER_USER='repluser',
    MASTER_PASSWORD='replsecret',
    MASTER_CONNECT_RETRY=10;